# Generated by Django 4.2.11 on 2024-09-01 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_artiste')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_artiste-type')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artist', verbose_name='ID_artiste')),
            ],
            options={
                'db_table': 'artiste_type',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_localité')),
                ('code_postal', models.CharField(max_length=12, unique=True, verbose_name='Code postal')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom de la localité')),
            ],
            options={
                'verbose_name': 'Localité',
                'verbose_name_plural': 'Localités',
                'db_table': 'localities',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_lieu')),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('designation', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.locality', verbose_name='locations')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_representation')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.location', verbose_name='ID_lieu')),
            ],
            options={
                'db_table': 'representations',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_role')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nom du rôle')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_spectacle')),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='show/')),
                ('bookable', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='catalogue.location')),
            ],
            options={
                'db_table': 'shows',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_type')),
                ('type', models.CharField(max_length=60, verbose_name='Fonction_artiste')),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_user')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('langue', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_tag')),
                ('tag', models.TextField(max_length=30, unique=True, verbose_name='Mot_cle')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.show', verbose_name='ID_spectacle')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_role-user')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.role', verbose_name='role_user')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.user', verbose_name='ID_user')),
            ],
            options={
                'db_table': 'role_user',
            },
        ),
        migrations.CreateModel(
            name='RepresentationUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_representation-user')),
                ('representation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.representation', verbose_name='ID_representation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.user', verbose_name='ID_user')),
            ],
            options={
                'db_table': 'representation_user',
            },
        ),
        migrations.AddField(
            model_name='representation',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.show', verbose_name='ID_spectacle'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.order')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.show')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_items',
            field=models.ManyToManyField(through='catalogue.OrderItem', to='catalogue.show'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_collaboration')),
                ('artist_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artisttype', verbose_name='Artiste_type')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.show', verbose_name='Shows')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.show')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistTypeShow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_artiste-type-show')),
                ('artist_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.artisttype', verbose_name='ID_artiste-type')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.show', verbose_name='ID_spectacle')),
            ],
            options={
                'db_table': 'artiste_type_show',
            },
        ),
        migrations.AddField(
            model_name='artisttype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.type', verbose_name='Fonction_artiste'),
        ),
    ]
