# Generated by Django 4.2.11 on 2024-09-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_video')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
