# Generated by Django 4.2.11 on 2024-09-01 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='show',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.show', verbose_name='ID_show'),
        ),
    ]
