# Generated by Django 4.2.11 on 2024-09-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_video_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troupe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_troupe')),
                ('name', models.TextField(max_length=255, unique=True)),
                ('logo_url', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'troupes',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='troupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.troupe', verbose_name='ID_troupe'),
        ),
    ]
