# Generated by Django 3.2.24 on 2024-03-18 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_artiste'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_localité'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_lieu'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.locality', verbose_name='locations'),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_spectacle'),
        ),
        migrations.AlterField(
            model_name='show',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.location', verbose_name='shows'),
        ),
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=60, verbose_name='Fonction_artiste'),
        ),
    ]
