# Generated by Django 3.2.24 on 2024-03-19 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20240318_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_artiste-type')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artist', verbose_name='ID_artiste')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.type', verbose_name='Fonction_artiste')),
            ],
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_collaboration')),
                ('artist_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artisttype', verbose_name='Artiste_type')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.show', verbose_name='Shows')),
            ],
        ),
    ]
