# Generated by Django 3.2.24 on 2024-03-19 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_artisttype_collaboration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='posterUrl',
        ),
        migrations.AddField(
            model_name='show',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='show/'),
        ),
        migrations.AlterField(
            model_name='show',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='catalogue.location'),
        ),
    ]
