# Generated by Django 5.0.3 on 2024-04-04 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_orderitem_order_ordered_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
