# Generated by Django 4.2.11 on 2024-03-31 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_user_alter_artisttype_table_artisttypeshow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisttypeshow',
            name='artist_type_show',
        ),
        migrations.AddField(
            model_name='artisttypeshow',
            name='artist_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.artisttype', verbose_name='ID_artiste-type'),
        ),
        migrations.AlterField(
            model_name='artisttypeshow',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_artiste-type-show'),
        ),
        migrations.AlterField(
            model_name='artisttypeshow',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.show', verbose_name='ID_spectacle'),
        ),
    ]
