# Generated by Django 4.2.11 on 2024-04-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_remove_artisttypeshow_artist_type_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='code_postal',
            field=models.CharField(max_length=12, unique=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='nom',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom de la localité'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_representation'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.location', verbose_name='ID_lieu'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.show', verbose_name='ID_spectacle'),
        ),
        migrations.AlterField(
            model_name='representationuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_representation-user'),
        ),
        migrations.AlterField(
            model_name='representationuser',
            name='representation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.representation', verbose_name='ID_representation'),
        ),
        migrations.AlterField(
            model_name='representationuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.user', verbose_name='ID_user'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_role'),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_role-user'),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.role', verbose_name='role_user'),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.user', verbose_name='ID_user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_user'),
        ),
    ]
