# Generated by Django 4.2.11 on 2024-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_alter_locality_code_postal_alter_locality_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='when',
            field=models.DateTimeField(null=True),
        ),
    ]
