# Generated by Django 4.2.11 on 2024-04-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_representation_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='when',
        ),
    ]
