# Generated by Django 4.2.11 on 2024-05-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_remove_representation_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID_tag')),
                ('type', models.TextField(max_length=30, unique=True, verbose_name='Mot_cle')),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.show', verbose_name='ID_spectacle')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
